---
title: "CS422-Homework 1"
output: 
  html_notebook:
    toc: yes
    toc_float: yes
author: Sohaib Syed, A20439074
---

<!-- More information in R Markdown can be found at:
1. https://www.ssc.wisc.edu/sscc/pubs/RFR/RFR_RMarkdown.html  This is 
   the place to start since it is a short tutorial.
2. https://rmarkdown.rstudio.com/index.html This contains a longer 
   tutorial.  Take a look at the cheatsheet in 
   https://rmarkdown.rstudio.com/lesson-15.html, it is a concise 
   reference of R Markdown on two pages.
<-->

### Part 2.1-A
```{r}
library(dplyr)
colleges=read.csv(file="College.csv",header=TRUE,stringsAsFactors = FALSE,sep=",",row.names=1)
colleges[1:5,c(1,5,8,10)]
```

### Part 2.1-B.

```{r}
private<-sum(colleges$Private=="Yes")
public<-sum(colleges$Private=="No")
str <- paste0("There are ", private, " private colleges, and ", public, " public colleges in the dataset")
str

```
### Part 2.1-C
```{r}
colleges1=read.csv(file="College.csv",row.names=1)[,c("Private","Apps","Enroll","PhD","perc.alumni", "S.F.Ratio","Grad.Rate")]
colleges1[1:6,]
```

### Part 2.1-D-i
```{r}
private<- (filter(colleges1, Private =="Yes"))
phd_priv_hist<-hist(private$PhD,plot=F)
phd_priv_hist
```
### Part 2.1-D-ii
```{r}
public<- (filter(colleges1, Private =="No"))
phd_pub_hist<-hist(public$PhD,plot=F)
phd_pub_hist
```
### Part 2.1-D-iii
```{r}
priv_color<-rainbow(n=10)
pub_color<-rainbow(n=9)
plot(phd_priv_hist,col=priv_color,main="Number of private colleges and percentage of faculty with PhD's",xlab= "Percentage of faculty with PhD's", ylab= " Number of colleges")
plot(phd_pub_hist,col=pub_color,main="Number of public colleges and percentage of faculty with PhD's",xlab= "Percentage of faculty with PhD's", ylab= " Number of colleges")
```

### Part 2.1-E-i
```{r}
minimumGrad<- colleges1[order((colleges1$Grad.Rate)),]
minimumGrad[1:5,]
```
### Part 2.1-E-ii
```{r}
maximumGrad<- colleges1[order(-(colleges1$Grad.Rate)),]
maximumGrad[1:5,]
```
### Part 2.1-F-i
```{r}
library("psych")
pairs.panels(colleges1[,c("Grad.Rate","PhD","S.F.Ratio")])
```
### Part 2.1-F-ii
```
Graduation Rate and and percentage of faculty with PhD's is the highest positive correlation. This does make sense as it might infer that professors that have their PhD's are better able to teach and therefore the students are more likely to pass classes.
   
```
### Part 2.1-F-iii
```
The lowest negative correlation is S.F. Ratio and Graduation Rate. This would make sense as well as there are more students the possibility of all of them gradutaing decreases. It also could infer that when there aren't that many faculty members students have a harder time getting help. 

```

### Part 2.1-G
```{r}
boxplot(perc.alumni~Private,data=colleges,xlab="Private School",ylab= "Percentage of alumni who donate",main="Percentage of alumni who donate")
```

### Part 2.1-H-i
```{r}
plot(main="Percentage of students that pay certain amounts for college", xlab= "Expenditure", ylab= "Percentage of students",ecdf(colleges$Expend))
grid()
```
### Part 2.1-H-ii
```
The median expenditure seems to be about 9000

```
### Part 2.1-H-ii
```
It seems that 80% of the students pay less than $12000

```