---
title: "CS 422-Homework 2"
output: 
  html_notebook:
    toc: yes
    toc_float: yes
author: Sohaib Syed, A20439074
---

### Part 2.1-A
```{r}
df<- read.csv(file="us-covid-deaths.csv")
df_complete<- df[complete.cases(df), ]
df_complete [1:6,]
```

### PArt 2.1-B
```{r}
library("psych")
pairs.panels(df_complete)
```
### PArt 2.1-B-i
```
The highest postivie correlation that the response variable has is with the total_tests. the coefficient of this is 0.99.
```
### PArt 2.1-B-ii
```
The lowest neagtive correlation that the response variable has is with the stingency_index. The coefficient of this is -0.66.
```
### PArt 2.1-B-iii
```
The correlation in part i is a good example that correlation is not causation, as it wouldn't make sense that tests are causing deaths. Part ii shows a correlation that makes sense, that as the country got more strict in preventing the spread, the deaths decreased. 
```
### PArt 2.1-C
```{r}

covid_regress_model<-lm( total_deaths ~ . - date, data=df_complete)
plot(residuals(covid_regress_model), main="Residuals")

summary(covid_regress_model)
rss<-c(crossprod(covid_regress_model$residuals))
rss
```
### PArt 2.1-D
```
The linear model is good considering that the F-statistic is greater than 1 and that the Adjusted R-squared is very high.  
```
### PArt 2.1-E
```
The summary indicates that the follwoing predictors are significant:
icu_patients      
stringency_index   
reproduction_rate 
total_tests        
positive_rate
```
### PArt 2.1-F
```
The summary shows that hosp_patients is not statsitically significant. This is because if a patient is in the hospital then they aren't dead, and a dead person isn't going to be at a hospital, at least not for long.
```
### PArt 2.1-G
```{r}
df_removed_predictor<-df_complete[,c(-1,-7)]
g<-lm(df_removed_predictor)
plot(residuals(g), main="Residuals")

grss<-c(crossprod(g$residuals))
grss
# This model seems to be worse than the one from part 2.1-C because the F-statistic is much lower and the adjusted R^2 value is about 33% lower as well.
```
